Debug-Enabled: false
Setting:
  Disable-Mount: true
  Disable-BoneMeal: true
  Reduce-ArrowDamage: #player
    Enabled: true
    Percent: 0.5
  Respawn-KeepState:
    Enabled: true
    Min-Health: 6
  ReplaceNoDamageTicks:
    Enabled: true
    Ticks: 5
  KeepGlowingEffect:
    Enabled: true
  DisplayItem:
    Enabled: true
    Cooldown: 5
  ShowDeathLocation:
    Enabled: true
  MendingEnchant:
    Enabled: true
    Chance: 0.01
  FixHealthRegen:
    Enabled: false

Kill-Point-Setting:
  Enabled: true
  DistributionKillPointExp: true
  Fix-DeathEvent: false
  Required-Exp: 800
  PerEntity-MaxExpValue: 1600
  KillPointExpEquations: "((H*0.25)+(D*3)+(A*1.5)+(AT*2))"
  KillPointExpSpread: 0.25

SpawnLocation: ""
CraftingEquipment:
  DefenseEquations: "DA * (1 - (DE / (5 * DA + DE)))"
  MaxKillPoint: 10
  SpecialAbility:
    KillPoint: 2
  MeleeDamage:
    KillPoint: 1
    AddRange: "0:2"
    RemoveRange: "0:1"
  ProjectileDamage:
    KillPoint: 1
    AddRange: "0:2"
    RemoveRange: "0:1"
  Defense:
    KillPoint: 1
    AddRange: "0:4"
    RemoveRange: "0:2"
  AttackSpeed:
    KillPoint: 1
    AddRange: "0:0.3"
    RemoveRange: "0:0.15"
  MaxHealth:
    KillPoint: 1
    AddRange: "0:2"
    RemoveRange: "0:1"
KillPoint-Shop:
  MoveSpawn:
    Enabled: true
    Required-KillPoint: 1
    Material: Compass
    Name: 스폰 이동
    Lore:
      - '&e필요 킬 포인트: &7 <requiredKillPoint>'
      - ''
      - '&f스폰 지점으로 이동'
  BackDeathLocation:
    Enabled: true
    Required-KillPoint: 1
    Material: Skeleton_skull
    Name: '&f마지막으로 죽은 위치로 이동'
    Lore:
      - '&e필요 킬 포인트: &7 <requiredKillPoint>'
      - ''
      - '&f마지막으로 죽은 위치로 이동'
  RerollSpecialAbility:
    Enabled: true
    Required-KillPoint: 1
    Material: black_banner
    Name: '&f제작 장비 특수 능력 재설정'
    Lore:
      - '&e필요 킬 포인트: &7 <requiredKillPoint>'
      - ''
      - '&f손에있는 제작장비의 특수 능력을 재설정 한다.'
      - ''
      - '&f제작 장비의 특수 능력이 없을 경우 사용 불가'
  ApplySpecialAbility:
    Enabled: true
    Required-KillPoint: 4
    Material: white_banner
    Name: '&f제작 장비 특수 능력 부여'
    Lore:
      - '&e필요 킬 포인트: &7 <requiredKillPoint>'
      - ''
      - '&f손에있는 제작장비에 특수 능력을 부여한다.'
      - ''
      - '&f제작 장비의 특수능력이 없을 경우 사용가능.'