package me.msicraft.modpackintegrated.CraftingEquip.Enum;

public enum SpecialAbility {
    doubleDamage_5,doubleDamage_10,doubleDamage_15,lifeDrain_5_5,lifeDrain_5_10,lifeDrain_10_5,lifeDrain_10_10,extraDamage_0_2,extraDamage_0_4,extraDamage_0_6
    ,extraDamagePlayerBaseHealth_1,extraDamagePlayerBaseHealth_3,extraDamagePlayerBaseHealth_5
    ,extraAttackSpeed_5,extraAttackSpeed_10,extraAttackSpeed_15,extraMovementSpeed_5,extraMovementSpeed_10,extraDamageToDay_5,extraDamageToDay_10,extraDamageToDay_15
    ,extraDamageToNight_5,extraDamageToNight_10,extraDamageToNight_15,extraDamageFullHealth_20,extraDamageFullHealth_25
}
